name: test workflow
on:
  workflow_dispatch:
env:
  LAST_WEEK_START: $(date + "%Y-%m-%d" --date='1 days ago')
  LAST_WEEK_END: $(date + "%Y-%m-%d" --date='7 days ago')
jobs:
  sandbox-operation:
    name: test 
    runs-on: ubuntu-latest
    steps:

      - name: Echo current date
        run: |
          echo ${{ env.LAST_WEEK_START }}
          echo ${{ env.LAST_WEEK_END }}
