name: test workflow
on:
  workflow_dispatch:
env:
  LAST_WEEK_START: date --date='1 day ago'
  LAST_WEEK_END: date --date='7 day ago'
jobs:
  sandbox-operation:
    name: test 
    runs-on: ubuntu-latest
    steps:
      - name: Echo current date
        run: |
          echo ${{ env.LAST_WEEK_START+%Y-%m-%dT }}
