name: test workflow
on:
  workflow_dispatch:
env:
  LAST_WEEK_START: $(date -d "yesterday" +'%Y-%m-%d')
  LAST_WEEK_END: $(date -d "7 days ago" +'%Y-%m-%d')
jobs:
  sandbox-operation:
    name: test 
    runs-on: ubuntu-latest
    steps:
      - name: Echo current date
        run: |
          echo ${{ env.LAST_WEEK_START }}
          echo ${{ env.LAST_WEEK_END }}
          
      - name: Get dates for the last 4 months excluding the current month
        run: |
          # Loop through the last 4 months (excluding the current month)
          for i in {1..4}; do
            # Get the first day of the current month - i months ago
            START_DATE=$(date -d "$(date +'%Y-%m-01') -$i month" +'%Y-%m-%d')
            
            # Get the last day of the current month - i months ago
            END_DATE=$(date -d "$(date +'%Y-%m-01') -$i month +1 month -1 day" +'%Y-%m-%d')
            
            echo "Month $i: Start Date = $START_DATE, End Date = $END_DATE"
            
            # Optionally, store them in environment variables for later steps
            echo "START_DATE_$i=$START_DATE" >> $GITHUB_ENV
            echo "END_DATE_$i=$END_DATE" >> $GITHUB_ENV
          done


      - name: Get dates for the last 6 weeks excluding the current week
        run: |
          # Loop through the last 6 weeks (excluding the current week)
          for i in {1..6}; do
            # Get the start date of the week (i weeks ago)
            START_DATE=$(date -d "last Sunday -$i week +1 day" +'%Y-%m-%d')
            
            # Get the end date of the week (i weeks ago)
            END_DATE=$(date -d "last Sunday -$i week" +'%Y-%m-%d')
            
            echo "Week $i: Start Date = $START_DATE, End Date = $END_DATE"
            
            # Optionally, store them in environment variables for later steps
            echo "START_WEEK_$i=$START_DATE" >> $GITHUB_ENV
            echo "END_WEEK_$i=$END_DATE" >> $GITHUB_ENV
          done

      - name: Show stored environment variables
        run: |
          # Display all start and end dates for the last 4 months
          echo "Month 1: Start Date = ${{ env.START_DATE_1 }}, End Date = ${{ env.END_DATE_1 }}"
          echo "Month 2: Start Date = ${{ env.START_DATE_2 }}, End Date = ${{ env.END_DATE_2 }}"
          echo "Month 3: Start Date = ${{ env.START_DATE_3 }}, End Date = ${{ env.END_DATE_3 }}"
          echo "Month 4: Start Date = ${{ env.START_DATE_4 }}, End Date = ${{ env.END_DATE_4 }}" 
          echo "--------------"
          echo "Week 1: Start Date = ${{ env.START_WEEK_1 }}, End Date = ${{ env.END_WEEK_1 }}"
          echo "Week 2: Start Date = ${{ env.START_WEEK_2 }}, End Date = ${{ env.END_WEEK_2 }}"
          echo "Week 3: Start Date = ${{ env.START_WEEK_3 }}, End Date = ${{ env.END_WEEK_3 }}"
          echo "Week 4: Start Date = ${{ env.START_WEEK_4 }}, End Date = ${{ env.END_WEEK_4 }}" 
          echo "Week 5: Start Date = ${{ env.START_WEEK_5 }}, End Date = ${{ env.END_WEEK_5 }}" 
          echo "Week 6: Start Date = ${{ env.START_WEEK_6 }}, End Date = ${{ env.END_WEEK_6 }}" 

